---
workspace:
  base: /go
  path: src/github.com/${DRONE_REPO}

pipeline:
  test:
    image: golang:1.8
    commands:
      - mkdir -p /go/bin
      - "curl -s https://glide.sh/get | sh"
      - glide install
      - go get github.com/vektra/mockery/.../
      - go generate $(go list ./... | grep -v /vendor)
      - go vet $(go list ./... | grep -v /vendor)
      - go test -v -cover $(go list ./... | grep -v /vendor)
      - go build $(go list ./... | grep -v /vendor)

  test-e2e:
    image: golang:1.8
    environment:
      - KETO_ASSETS_DIR=/ketoassets
      - CLUSTER_NAME=drone-build-${DRONE_BUILD_NUMBER}
    commands:
      - ./bin/keto_test_e2e.sh
    when:
      event: deployment
